version: "4"

services:
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - /path/to/local/d–∞ta:/root/redis
#      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
#
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#
#  server:
#    build: server/
#    ports:
#      - "8080:8080"